SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
SCREEN_TITLE = "Asteroids"

SHIP_TURN_SPEED = 3
SHIP_THRUST = 0.15
SHIP_DRAG = 0.98
SHIP_RADIUS = 15
SHIP_INVULNERABILITY_TIME = 180

ASTEROID_LARGE_RADIUS = 50
ASTEROID_MEDIUM_RADIUS = 30
ASTEROID_SMALL_RADIUS = 15
ASTEROID_BASE_SPEED = 1.5
STARTING_ASTEROIDS = 4

BULLET_SPEED = 7
BULLET_LIFE = 60
BULLET_RADIUS = 3

SCORE_LARGE = 20
SCORE_MEDIUM = 50
SCORE_SMALL = 100
